{{- range .Values.shareProtocols }}
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: {{ $.Values.driverName }}
spec:
  attachRequired: false
  podInfoOnMount: false
---
{{- end }}
